create table `ENDERECO`(

    ID bigint not null auto_increment primary key,
    LOGRADOURO VARCHAR(100),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(50),
    CEP VARCHAR(15),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(30),
    COLEGIO_ID bigint,
    RESPONSAVEL_ID bigint,
    ALUNO_ID bigint,
        FOREIGN KEY (COLEGIO_ID) REFERENCES COLEGIO(ID),
        FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO(ID),
        FOREIGN KEY (RESPONSAVEL_ID) REFERENCES RESPONSAVEL(ID)
    );

